name: GitHub Actions Lint
description: Lint GitHub Actions workflows

runs:
  using: composite
  steps:
    - name: actionlint
      uses: koki-develop/github-actions-lint/actionlint@cd40a2834e54895146e4a73ae17dcc37944ffb0f # v1.1.0
      if: ${{ !cancelled() }}

    - name: ghalint
      uses: koki-develop/github-actions-lint/ghalint@cd40a2834e54895146e4a73ae17dcc37944ffb0f # v1.1.0
      if: ${{ !cancelled() }}

    - name: zizmor
      uses: koki-develop/github-actions-lint/zizmor@cd40a2834e54895146e4a73ae17dcc37944ffb0f # v1.1.0
      if: ${{ !cancelled() }}
