name: GitHub Actions Lint
description: Lint GitHub Actions workflows

runs:
  using: composite
  steps:
    - name: actionlint
      uses: koki-develop/github-actions-lint/actionlint@a4634895b43225531015f69d2703686686adeec4 # v1.0.1
      if: ${{ !cancelled() }}

    - name: ghalint
      uses: koki-develop/github-actions-lint/ghalint@a4634895b43225531015f69d2703686686adeec4 # v1.0.1
      if: ${{ !cancelled() }}

    - name: zizmor
      uses: koki-develop/github-actions-lint/zizmor@a4634895b43225531015f69d2703686686adeec4 # v1.0.1
      if: ${{ !cancelled() }}
