services:
  actionlint:
    build:
      context: ./dockerfiles/actionlint
      dockerfile: ./Dockerfile
    volumes:
      - .:/repo

  ghalint:
    build:
      context: ./dockerfiles/ghalint
      dockerfile: ./Dockerfile
    volumes:
      - .:/repo

  zizmor:
    build:
      context: ./dockerfiles/zizmor
      dockerfile: ./Dockerfile
    volumes:
      - .:/repo
