name: ghalint
description: Lint GitHub Actions workflows with ghalint

inputs:
  action-path:
    description: |
      Path to action.yml.
      This is passed to `ghalint run-action`.
    required: false

runs:
  using: docker
  image: docker://ghcr.io/koki-develop/github-actions-lint/ghalint:0.0.3
  args:
    - ${{ inputs.action-path }}
