name: Publish Image

permissions: {}

on:
  workflow_call:
    inputs:
      component-version: # e.g. "actionlint-v1.2.3"
        type: string
        required: true

jobs:
  publish:
    name: Publish Docker image
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Extract component
        id: component
        env:
          COMPONENT_VERSION: ${{ inputs.component-version }} # e.g. "actionlint-v1.2.3"
        run: |
          {
            echo "name=${COMPONENT_VERSION%-*}"
            echo "version=${COMPONENT_VERSION#*-}"
          } >> "$GITHUB_OUTPUT"

      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/${{ steps.component.outputs.name }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ steps.component.outputs.version }}
            type=sha,format=long

      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with: # zizmor: ignore[template-injection]
          context: ./dockerfiles/${{ steps.component.outputs.name }}
          file: ./dockerfiles/${{ steps.component.outputs.name }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
